
origin $003D0951
dialogue_kage:
	dialogue_text_start(" A MARTIAL ARTS SUPERSTAR TRAINED")
	dialogue_text("BY  GREAT  MASTERS FROM AROUND THE")
	dialogue_text(" WORLD.")
	dialogue_text("     CAGE USES HIS TALENTS ON")
	dialogue_text(" THE BIG SCREEN, HE IS THE CURRENT")
	dialogue_text("BOX-OFFICE CHAMP AND STAR OF SUCH")
	dialogue_text("MOVIES AS DRAGON FIST AND DRAGON")
	dialogue_text("  FIST II AS WELL AS THE AWARD")
	dialogue_text("    WINNING SUDDEN VIOLENCE.")
	end()
	db ($02)
	db ($03)
	db ($11)	
dialogue_kano:
	dialogue_text_start("	  A MERCENARY, THUG EXTORTIONIST")
	dialogue_text("THIEF - KANO LIVES A LIFE OF CRIME")
	dialogue_text("         AND INJUSTICE.")
	dialogue_text("  HE IS A DEVOTED MEMBER OF THE")
	dialogue_text(" BLACK DRAGON, A DANGEROUS GROUP")
	dialogue_text(" OF CUT-THROAT MADMEN FEARED AND")
	dialogue_text("   RESPECTED THROUGHOUT ALL OF")
	dialogue_text("      CRIME'S INNER CIRCLES.")
		end()
		db ($02)
		db ($03)
		db ($11)
dialogue_raiden:
	dialogue_text_start("THE NAME RAIDEN IS ACTUALLY THAT")
	dialogue_text("     OF A DEITY KNOWN AS")
	dialogue_text("       THE THUNDER GOD.")
	break_line()
	dialogue_text("   IT IS RUMORED HE RECEIVED A ")
	dialogue_text("PERSONAL INVITATION BY SHANG TSUNG")
	dialogue_text("  HIMSELF AND TOOK THE FORM OF A")
	dialogue_text("HUMAN TO COMPETE IN THE TOURNAMENT.")
		end()
		db ($02)
		db ($03)
		db ($11)
dialogue_liu_kang:
	dialogue_text_start("ONCE A MEMBER OF THE SUPER SECRET")
	dialogue_text("WHITE LOTUS SOCIETY, LIU KANG LEFT")
	dialogue_text("   THE ORGANIZATION IN ORDER TO")
	dialogue_text("     REPRESENT SHAOLIN TEMPLES")
	dialogue_text("        IN THE TOURNAMENT.")
	break_line()
	dialogue_text("      KANG IS STRONG IN HIS")
	dialogue_text(" BELIEFS AND DESPISES SHANG TSUNG.")
		end()
		db ($02)
		db ($03)
		db ($11)
dialogue_scorpion:
	dialogue_text_start("	LIKE SUB-ZERO, SCORPION'S TRUE")
	dialogue_text("   NAME AND ORIGIN ARE NOT KNOWN.")
	break_line()
	dialogue_text("  HE HAS SHOWN FROM TIME TO TIME")
	dialogue_text("   DISTRUST AND HATRED TOWARDS")
	dialogue_text("            SUB-ZERO.")
	break_line()
	dialogue_text(" BETWEEN NINJAS, THIS IS USUALLY")
	dialogue_text("     A SIGN OF OPPOSING CLANS.")
		end()
		db ($02)
		db ($03)
		db ($12)
dialogue_sub_zero:
		dialogue_text_start("THE ACTUAL NAME OR IDENTITY OF")
		dialogue_text("     THIS WARRIOR IS UNKNOWN.")
		break_line()
		dialogue_text("   HOWEVER BASED ON THE MARKINGS")
		dialogue_text("OF HIS UNIFORM, IT IS BELIEVED HE")
		dialogue_text("      BELONGS TO THE LIN KUEI,")
		dialogue_text("A LEGENDARY CLAN OF CHINESE NINJA.")
		end()
		db ($02)
		db ($03)
		db ($11)

dialogue_sonya:
		dialogue_text_start("	SONYA IS A MEMBER OF A TOP U.S.")
		dialogue_text("SPECIAL FORCES UNIT. HER TEAM WAS")
		dialogue_text("HOT ON THE TRAIL OF KANO'S BLACK")
		dialogue_text("       DRAGON ORGANIZATION.")
		break_line()
		dialogue_text("THEY FOLLOWED THEM TO AN UNCHARTED")
		dialogue_text(" ISLAND WHERE THEY WERE AMBUSHED")
		dialogue_text(" BY SHANG TSUNG'S PERSONAL ARMY.")
		end()
		db ($02)
		db ($03)
		db ($11)