
origin $003D10E0
dialogue_intro:
	db ($01)
	db ($FD)
	db ($04)
	db ($FC)
	dialogue_text_intro("GORO LIVES...")
	db ($FE)
	db ($FD)
	db ($07)
	dialogue_text_intro("A 2,000 YEAR OLD HALF HUMAN DRAGON")
	db ($FE)
	db ($FD)
	db ($09)
	dialogue_text_intro("GORO REMAINS UNDEFEATED FOR THE PAST")
	db ($FE)
	db ($FD)
	db ($0B)
	dialogue_text_intro("500 YEARS. HE WON THE TITLE OF GRAND")
	db ($FE)
	db ($FD)
	db ($0D)
	dialogue_text_intro("CHAMPION BY DEFEATING KUNG LAO, A")
	db ($FE)
	db ($FD)
	db ($0F)
	dialogue_text_intro("SHAOLIN FIGHTING MONK. IT WAS DURING")
	db ($FE)
	db ($FD)
	db ($11)
	dialogue_text_intro("THIS PERIOD THAT THE TOURNAMENT FELL")
	db ($FE)
	db ($FD)
	db ($13)
	dialogue_text_ibtro("INTO SHANG TSUNG'S HANDS AND WAS")
	db ($FE)
	db ($FD)
	db ($15)
	dialogue_text_intro("CORRUPTED...")
	end()